# Generated by Django 6.0.6 on 2026-06-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='building',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='house',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='street',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='structure',
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('phone', 'Телефон'), ('address', 'Адрес')], default='address', max_length=20, verbose_name='Контактные данные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='value',
            field=models.CharField(default='не указано', max_length=200, verbose_name='Значение'),
            preserve_default=False,
        ),
    ]
