# Generated by Django 6.0.6 on 2026-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_created_at_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
    ]
