name: Tests and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: diplom_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: diplom_db
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.14'
    - name: Install dependencies
      run: pip install -r requirements.txt coverage
    - name: Run tests
      env:
        DJANGO_SECRET_KEY: test-key
        DB_NAME: diplom_db
        DB_USER: diplom_user
        DB_PASSWORD: password
        DB_HOST: localhost
        DB_PORT: 5432
      run: coverage run manage.py test diplom.tests
    - name: Report coverage
      run: coverage report -m