# Generated by Django 6.0.6 on 2026-06-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Внешний ID.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.PositiveIntegerField(verbose_name='Внешний ID.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=200, verbose_name='Модель.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_rrc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Рекомендованная цена.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество.'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название характеристики.'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.CharField(max_length=500, verbose_name='Значение.'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Принимает заказы.'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название магазина.'),
        ),
    ]
