# Generated by Django 6.0.6 on 2026-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_external_id_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='external_id',
        ),
        migrations.AddField(
            model_name='category',
            name='shops',
            field=models.ManyToManyField(related_name='categories', to='products.shop', verbose_name='Магазины'),
        ),
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Характеристика.'),
        ),
    ]
