# Generated by Django 6.0.6 on 2026-06-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_external_id_category_shops_shop_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Внешний ID'),
        ),
    ]
