# Generated by Django 6.0.6 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Внешний ID'),
        ),
    ]
